spring.application.name=access-control
server.port=8083

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:9582}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/access-control-database}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=N0DtuQO01oO09vvD76khJW8TUJGt7df4LZDtObEtk2v